version: '3'

services: 
  namesrv:
    image: apache/rocketmq:4.8.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    command: sh mqnamesrv
  
  broker:
    image: apache/rocketmq:4.8.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - ./conf/broker.properties:/home/rocketmq/broker.properties
    command: sh mqbroker -n namesrv:9876 -c /home/rocketmq/broker.properties
    depends_on:
      - namesrv
  
  mqconsole:
    image: candice0630/rocketmq-console-ng:2.0
    container_name: rmqconsole
    ports:
      - 19876:8080
    environment:
      JAVA_OPTS: -Drocketmq.config.namesrvAddr=namesrv:9876 -Drocketmq.config.isVIPChannel=false
    depends_on:
      - namesrv


